# --- Standard Library ---
import os
import asyncio
import json

# --- Third-Party Libraries ---
import nest_asyncio

# --- Application Config & Constants ---
from constants import (
    CSV_FILE_PATH,
    ORDER_FILE_PATH,
    HISTORY_DIR,
    OLLAMA_MODEL,
    ENABLE_MEMORY,
    STORE_METADATA_FILE,
)

# --- Load Tool Definitions ---
from core.config import TOOL_DEFINITIONS, AVAILABLE_FUNCTIONS

# --- Core Application Modules ---
from core.tools.query_documents import query_documents, set_documents_retriever
from core.tools.query_memory import query_memory, set_memory_retriever
from core.vector_store import vector_store
from core.memory import ChatHistoryManager
from core.agent import run_agent
from core.utils import log_available_tools

from langchain_core.vectorstores import VectorStoreRetriever
from typing import Optional, Tuple

# --- Logging ---
from logging_config import setup_logger

# Initialize logger
logger = setup_logger(__name__)

# Global variables for the retrievers
document_retriever: Optional[VectorStoreRetriever] = None
memory_retriever: Optional[VectorStoreRetriever] = None

# --- Main Execution Block ---
async def main():    
    global document_retriever, memory_retriever
    
    try:
        # display tool definitions
        log_available_tools()
        
        # Initialize memory with session-based storage
        memory = ChatHistoryManager(
            max_history=15,
            history_dir=HISTORY_DIR
        )

        # Initialize vector stores and retrievers
        logger.info("Initializing vector stores...")
        retrievers = vector_store(
            file_paths=[CSV_FILE_PATH, ORDER_FILE_PATH],
            enable_memory=ENABLE_MEMORY
        )
        
        # Unpack the tuple
        if isinstance(retrievers, tuple) and len(retrievers) == 2:
            document_retriever, memory_retriever = retrievers
        else:
            document_retriever = retrievers
            memory_retriever = None
            logger.warning("Vector store setup returned single retriever. Memory queries may be limited to session scope.")

        # Set the retrievers in their respective modules
        if document_retriever is not None:
            set_documents_retriever(document_retriever)
            
        if memory_retriever is not None:
            set_memory_retriever(memory_retriever)

        # Display initialization status
        display_initialization_status()

    except Exception as e:
        document_retriever = None
        memory_retriever = None
        logger.error(f"❌ Error during setup: {e}")

    # Display welcome message
    display_welcome_message()

    # Main interaction loop
    session_id = None  # Will be generated by run_agent if not provided
    while True:
        try:
            user_input = input("\nYou: ").strip()
            if not user_input:
                continue
            if user_input.lower() in ['exit', 'quit']:
                break

            async for response in run_agent(
                model=OLLAMA_MODEL,
                user_input=user_input,
                memory=memory,
                session_id=session_id
            ):
                if response.get("status") == "error":
                    logger.error(f"Error: {response.get('error', 'Unknown error')}")
                    continue
                
                if "message" in response:
                    if isinstance(response["message"], str):
                        print(f"\nAssistant: {response['message']}")
                    else:
                        print(f"\nAssistant: {json.dumps(response['message'], indent=2)}")
                elif "content" in response:
                    print(f"\nAssistant: {response['content']}")

        except KeyboardInterrupt:
            print("\nGoodbye! 👋")
            break
        except Exception as e:
            logger.error(f"Error: {e}")

def display_initialization_status():
    """Display the status of retriever initialization."""
    # Document retriever status
    if document_retriever is not None:
        doc_status_msg = (
            f"\n✅ Document Retriever successfully initialized!"
            f"\n   • Tags         : {getattr(document_retriever, 'tags', 'N/A')}"
            f"\n   • Vector Store : {type(getattr(document_retriever, 'vectorstore', 'N/A')).__name__}"
            f"\n   • Search Params: {getattr(document_retriever, 'search_kwargs', 'N/A')}"
        )
        logger.info(doc_status_msg)
    else:
        logger.error("❌ Document Retriever initialization failed. Document queries will not work.")

    # Memory retriever status
    if ENABLE_MEMORY:
        if memory_retriever is not None:
            memory_status_msg = (
                f"\n✅ Memory Retriever successfully initialized!"
                f"\n   • Tags         : {getattr(memory_retriever, 'tags', 'N/A')}"
                f"\n   • Vector Store : {type(getattr(memory_retriever, 'vectorstore', 'N/A')).__name__}"
                f"\n   • Search Params: {getattr(memory_retriever, 'search_kwargs', 'N/A')}\n"
            )
            logger.info(memory_status_msg)
        else:
            logger.info("\n📝 Memory retriever not initialized - memory queries will be session-based only\n")
    else:
        logger.info("\n📝 Memory is disabled. Conversation history will not be searchable.\n")

def display_welcome_message():
    """Display the welcome message."""
    print("\n" + "="*50)
    print("🤖 Welcome to the Pizza AI Assistant CLI!")
    print("Type 'exit' or 'quit' to end the session")
    print("="*50)

if __name__ == "__main__":
    try:
        nest_asyncio.apply()
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\nGoodbye! 👋")